import 'dart:io';
import 'dart:typed_data';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../models/match_state.dart';
import '../models/models.dart';

/// Builds a shareable PDF scorecard from a [MatchState] and hands it off
/// to the OS share sheet — including WhatsApp — via `share_plus`.
class PdfExportService {
  /// Generates the PDF, saves it to a temp file, and opens the native
  /// share sheet so the user can send it directly (e.g. as a WhatsApp
  /// attachment, email, or save to Drive).
  static Future<void> shareScorecard(MatchState state) async {
    final bytes = await _buildPdf(state);
    final dir = await getTemporaryDirectory();
    final safeName = '${state.teamA.name}_vs_${state.teamB.name}'
        .replaceAll(RegExp(r'[^A-Za-z0-9_]'), '_');
    final file = File('${dir.path}/scorecard_$safeName.pdf');
    await file.writeAsBytes(bytes, flush: true);

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      text: '${state.teamA.name} vs ${state.teamB.name} — Cricket Scoreboard',
      subject: 'Cricket Scorecard: ${state.teamA.name} vs ${state.teamB.name}',
    );
  }

  static Future<Uint8List> _buildPdf(MatchState s) async {
    final doc = pw.Document();

    // Prefer the frozen innings snapshots. If the match is still live and
    // no snapshot exists yet for the current innings, build one on the
    // fly from the live stats so an in-progress match can still be shared.
    final innings = s.analysisInnings.isNotEmpty
        ? s.analysisInnings
        : (s.battingStats.isNotEmpty
        ? [
      InningsRecord(
        battingTeam: s.battingTeam ?? 'A',
        bowlingTeam: s.bowlingTeam ?? 'B',
        score: s.score,
        wickets: s.wickets,
        oversStr: s.currentOversStr(),
        battingStats: s.battingStats,
        bowlingStats: s.bowlingStats,
        extras: s.extras,
        ballLog: s.ballLog,
      )
    ]
        : <InningsRecord>[]);

    final mom = s.manOfTheMatch();
    final title = '${s.teamA.name} vs ${s.teamB.name}';
    final resultText = _resultText(s);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Cricket Scoreboard',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
            pw.SizedBox(height: 4),
            pw.Divider(color: PdfColors.grey400),
          ],
        ),
        build: (context) => [
          pw.Text(title,
              style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text(resultText,
              style: const pw.TextStyle(fontSize: 13, color: PdfColors.grey800)),
          pw.SizedBox(height: 16),
          if (mom != null) _momBlock(mom),
          for (int i = 0; i < innings.length; i++) ...[
            pw.SizedBox(height: 14),
            _inningsBlock(s, innings[i]),
          ],
          if (innings.isEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 20),
              child: pw.Text(
                'No ball-by-ball data was recorded for this match.',
                style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
              ),
            ),
        ],
        footer: (context) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            'Generated by Cricket Scoreboard',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
        ),
      ),
    );

    return doc.save();
  }

  static String _resultText(MatchState s) {
    if (!s.matchOver) return 'Match in progress';
    if (s.firstInningsBattingTeam == null || s.firstInningsScore == null) {
      return 'Match ended';
    }
    final team1 = s.teamName(s.firstInningsBattingTeam!);
    final s1 = s.firstInningsScore!;
    final s2 = s.score;
    if (s2 > s1) {
      final wicketsLeft = s.totalWickets - s.wickets;
      return '${s.teamName(s.battingTeam!)} won by $wicketsLeft wicket${wicketsLeft == 1 ? '' : 's'}';
    } else if (s1 > s2) {
      return '$team1 won by ${s1 - s2} run${(s1 - s2) == 1 ? '' : 's'}';
    }
    return 'Match tied';
  }

  static pw.Widget _momBlock(PlayerPerformance mom) {
    final parts = <String>[
      if (mom.ballsFaced > 0) '${mom.runs} runs (${mom.ballsFaced} balls)',
      if (mom.ballsBowled > 0)
        '${mom.wickets}/${mom.runsConceded} (${mom.oversBowled} ov)',
    ];
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.amber700),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('PLAYER OF THE MATCH',
              style: pw.TextStyle(fontSize: 9, color: PdfColors.amber800)),
          pw.SizedBox(height: 3),
          pw.Text(mom.name,
              style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
          pw.Text(parts.join('  •  '), style: const pw.TextStyle(fontSize: 10)),
        ],
      ),
    );
  }

  static pw.Widget _inningsBlock(MatchState s, InningsRecord inn) {
    final battingRows = inn.battingStats.entries.map((e) {
      final bs = e.value;
      return [
        e.key,
        bs.out ? bs.howOut : 'not out',
        '${bs.runs}',
        '${bs.balls}',
        '${bs.fours}',
        '${bs.sixes}',
      ];
    }).toList();

    final bowlingRows = inn.bowlingStats.entries.map((e) {
      final bw = e.value;
      final econ = bw.legalBalls > 0 ? bw.runs / (bw.legalBalls / 6) : 0.0;
      return [e.key, bw.oversDisplay, '${bw.runs}', '${bw.wickets}', econ.toStringAsFixed(1)];
    }).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('${s.teamName(inn.battingTeam)} innings',
                style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
            pw.Text('${inn.score}/${inn.wickets}  (${inn.oversStr} ov)',
                style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
          ],
        ),
        pw.SizedBox(height: 6),
        pw.Table(
          border: const pw.TableBorder(
            horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          ),
          columnWidths: const {
            0: pw.FlexColumnWidth(3),
            1: pw.FlexColumnWidth(2),
            2: pw.FlexColumnWidth(1),
            3: pw.FlexColumnWidth(1),
            4: pw.FlexColumnWidth(1),
            5: pw.FlexColumnWidth(1),
          },
          children: [
            _tableHeaderRow(const ['Batter', 'Dismissal', 'R', 'B', '4s', '6s']),
            for (final row in battingRows)
              pw.TableRow(children: [
                _cell(row[0]),
                _cell(row[1], color: PdfColors.grey600, fontSize: 8),
                _cell(row[2], align: pw.TextAlign.right),
                _cell(row[3], align: pw.TextAlign.right),
                _cell(row[4], align: pw.TextAlign.right),
                _cell(row[5], align: pw.TextAlign.right),
              ]),
          ],
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          'Extras: ${inn.extras.total}  (b ${inn.extras.b}, lb ${inn.extras.lb}, '
              'w ${inn.extras.wd}, nb ${inn.extras.nb})',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 10),
        pw.Table(
          border: const pw.TableBorder(
            horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          ),
          columnWidths: const {
            0: pw.FlexColumnWidth(3),
            1: pw.FlexColumnWidth(1),
            2: pw.FlexColumnWidth(1),
            3: pw.FlexColumnWidth(1),
            4: pw.FlexColumnWidth(1),
          },
          children: [
            _tableHeaderRow(const ['Bowler', 'O', 'R', 'W', 'Econ']),
            for (final row in bowlingRows)
              pw.TableRow(children: [
                _cell(row[0]),
                _cell(row[1], align: pw.TextAlign.right),
                _cell(row[2], align: pw.TextAlign.right),
                _cell(row[3], align: pw.TextAlign.right),
                _cell(row[4], align: pw.TextAlign.right),
              ]),
          ],
        ),
      ],
    );
  }

  static pw.TableRow _tableHeaderRow(List<String> labels) {
    return pw.TableRow(
      decoration: const pw.BoxDecoration(color: PdfColors.grey200),
      children: labels
          .map((l) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 3),
        child: pw.Text(l,
            style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
      ))
          .toList(),
    );
  }

  static pw.Widget _cell(String text,
      {pw.TextAlign align = pw.TextAlign.left, PdfColor? color, double fontSize = 9}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3, horizontal: 3),
      child: pw.Text(text,
          textAlign: align, style: pw.TextStyle(fontSize: fontSize, color: color)),
    );
  }
}